/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.vitorAlves.adapters.ui;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.vitorAlves.application.gateways.BooksDAO;
import org.vitorAlves.application.usecases.InsertBook;
import org.vitorAlves.application.usecases.InsertBookByIsbn;
import org.vitorAlves.application.usecases.InsertBookDefault;
import org.vitorAlves.infra.gateways.JpaBooksDAO;

import java.awt.*;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author vitor-alves
 */
public class InsertFormUI extends javax.swing.JFrame {
    private static final Logger logger = LoggerFactory.getLogger(InsertFormUI.class);
    private final BooksDAO dao = new JpaBooksDAO();
    private final InsertBook insertBook = new InsertBookDefault(dao);
    private final InsertBook insertBookByIsbn = new InsertBookByIsbn(dao);
    
    /**
     * Creates new form DefaultInsertForm
     */
    public InsertFormUI(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        successDialog = new javax.swing.JDialog();
        successPanel = new javax.swing.JPanel();
        successLabel = new javax.swing.JLabel();
        closeSuccessButton = new javax.swing.JButton();
        errorDialog = new javax.swing.JDialog();
        errorPanel = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        closeErrorButton = new javax.swing.JButton();
        formPanel = new javax.swing.JPanel();
        typeInstructionLabel = new javax.swing.JLabel();
        bookDataLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        publishersLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        authorsLabel = new javax.swing.JLabel();
        authorsTextField = new javax.swing.JTextField();
        publishLabel = new javax.swing.JLabel();
        publishersTextField = new javax.swing.JTextField();
        isbnLabel = new javax.swing.JLabel();
        similarsLabel = new javax.swing.JLabel();
        similarTextField = new javax.swing.JTextField();
        findByIsbnLabel = new javax.swing.JLabel();
        isbnInstructions = new javax.swing.JLabel();
        fetchIsbnTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        publishDateChooser = new com.toedter.calendar.JDateChooser();
        isbnFormattedTextField = new javax.swing.JFormattedTextField();

        successPanel.setPreferredSize(new java.awt.Dimension(430, 50));
        successPanel.setLayout(new javax.swing.BoxLayout(successPanel, javax.swing.BoxLayout.X_AXIS));

        successLabel.setIcon(new javax.swing.ImageIcon("/home/vitor-alves/git/BooksManager/app/src/main/java/org/vitorAlves/adapters/assets/images/icons8-sucesso-48.png")); // NOI18N
        successLabel.setText("   O livro foi adicionado com sucesso!       ");
        successLabel.setName(""); // NOI18N
        successLabel.setPreferredSize(new java.awt.Dimension(60, 60));
        successPanel.add(successLabel);

        closeSuccessButton.setText("Fechar");
        closeSuccessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSuccessButtonActionPerformed(evt);
            }
        });
        successPanel.add(closeSuccessButton);

        successDialog.getContentPane().add(successPanel, java.awt.BorderLayout.CENTER);

        errorPanel.setMinimumSize(new java.awt.Dimension(430, 50));
        errorPanel.setPreferredSize(new java.awt.Dimension(430, 50));

        errorLabel.setIcon(new javax.swing.ImageIcon("/home/vitor-alves/git/BooksManager/app/src/main/java/org/vitorAlves/adapters/assets/images/icons8-erro-48.png")); // NOI18N
        errorPanel.add(errorLabel);

        closeErrorButton.setText("Fechar");
        closeErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeErrorButtonActionPerformed(evt);
            }
        });
        errorPanel.add(closeErrorButton);

        errorDialog.getContentPane().add(errorPanel, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Livro");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        formPanel.setBackground(new java.awt.Color(190, 190, 190));
        formPanel.setToolTipText("");
        formPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formPanel.setMinimumSize(new java.awt.Dimension(340, 200));
        formPanel.setPreferredSize(new java.awt.Dimension(430, 315));
        java.awt.GridBagLayout jPanel1Layout1 = new java.awt.GridBagLayout();
        jPanel1Layout1.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0};
        jPanel1Layout1.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        formPanel.setLayout(jPanel1Layout1);

        typeInstructionLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        typeInstructionLabel.setText("DIGITE...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        formPanel.add(typeInstructionLabel, gridBagConstraints);

        bookDataLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bookDataLabel.setText("Os dados do livro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        formPanel.add(bookDataLabel, gridBagConstraints);

        titleLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        titleLabel.setText("Título:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 60);
        formPanel.add(titleLabel, gridBagConstraints);

        publishersLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        publishersLabel.setText("Editoras:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 41);
        formPanel.add(publishersLabel, gridBagConstraints);

        titleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        formPanel.add(titleTextField, gridBagConstraints);

        authorsLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        authorsLabel.setText("Autores:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 45);
        formPanel.add(authorsLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        formPanel.add(authorsTextField, gridBagConstraints);

        publishLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        publishLabel.setText("Publicação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 23);
        formPanel.add(publishLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        formPanel.add(publishersTextField, gridBagConstraints);

        isbnLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        isbnLabel.setText("ISBN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 62);
        formPanel.add(isbnLabel, gridBagConstraints);

        similarsLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        similarsLabel.setText("Semelhantes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        formPanel.add(similarsLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        formPanel.add(similarTextField, gridBagConstraints);

        findByIsbnLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        findByIsbnLabel.setText("OU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        formPanel.add(findByIsbnLabel, gridBagConstraints);

        isbnInstructions.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        isbnInstructions.setText("Apenas o ISBN do livro e nós cuidaremos do resto!");
        isbnInstructions.setInheritsPopupMenu(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        formPanel.add(isbnInstructions, gridBagConstraints);

        fetchIsbnTextField.setPreferredSize(new java.awt.Dimension(200, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 5;
        formPanel.add(fetchIsbnTextField, gridBagConstraints);

        confirmButton.setBackground(new java.awt.Color(153, 255, 153));
        confirmButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        confirmButton.setText("Inserir");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.insets = new java.awt.Insets(9, 4, 0, 19);
        formPanel.add(confirmButton, gridBagConstraints);

        cancelButton.setBackground(new java.awt.Color(255, 153, 153));
        cancelButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(9, 1, 0, 0);
        formPanel.add(cancelButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 144);
        formPanel.add(publishDateChooser, gridBagConstraints);

        try {
            isbnFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        formPanel.add(isbnFormattedTextField, gridBagConstraints);

        getContentPane().add(formPanel);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void titleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextFieldActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        try {
            logger.info("Inserindo livro...");
            
            String fetchByIsbn = fetchIsbnTextField.getText().trim();
            if (!fetchByIsbn.equals("")) {
                insertBookByIsbn.execute(fetchByIsbn);
                displaySuccessDialog();
                dispose();
                logger.info("Operação de inserção bem sucedida!");
                return;
            }
                
            String title = titleTextField.getText().trim();

            String authorsText = authorsTextField.getText();
            List<String> authors = authorsText.equals("") ? 
                    Collections.emptyList() 
                    : Arrays.stream(authorsTextField.getText().split(";"))
                    .map(String::trim).collect(Collectors.toList());

            LocalDate publishDate = publishDateChooser.getDate().toInstant()
                    .atOffset(ZoneOffset.UTC).toLocalDate();

            String isbn = isbnFormattedTextField.getText().trim();

            String publishersText = publishersTextField.getText();
            List<String> publishers = publishersText.equals("") ? 
                    Collections.emptyList() :
                    Arrays.stream(publishersText.split(";"))
                    .map(String::trim).collect(Collectors.toList());

            String similarText = similarTextField.getText();
            List<String> similars = similarText.equals("") ?
                    Collections.emptyList() :
                    Arrays.stream(similarText.split(";"))
                    .map(String::trim).collect(Collectors.toList());
        
            insertBook.execute(title, authors, publishDate, isbn, publishers, similars);
            
            displaySuccessDialog();
            
            logger.info("Operação de inserção bem sucedida!");
            dispose();
        }
        catch (Exception e) {
            logger.error("Falha na inserção do livro!\n\t{}: {}", 
                    e.getClass().getSimpleName(), e.getMessage());
            errorLabel.setText("<html>Ocorreu um erro ao salvar o livro.<br>" +
                    "Verifique os logs da aplicação!</html>");
            errorDialog.setLocationRelativeTo(null);
            errorDialog.setMinimumSize(new Dimension(430, 60));
            errorDialog.setVisible(true);
        }
        
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        logger.warn("Operação cancelada");
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void closeSuccessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSuccessButtonActionPerformed
        successDialog.setVisible(false);
    }//GEN-LAST:event_closeSuccessButtonActionPerformed

    private void closeErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeErrorButtonActionPerformed
        errorDialog.setVisible(false);
    }//GEN-LAST:event_closeErrorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.error(ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InsertFormUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorsLabel;
    private javax.swing.JTextField authorsTextField;
    private javax.swing.JLabel bookDataLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton closeErrorButton;
    private javax.swing.JButton closeSuccessButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JTextField fetchIsbnTextField;
    private javax.swing.JLabel findByIsbnLabel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JFormattedTextField isbnFormattedTextField;
    private javax.swing.JLabel isbnInstructions;
    private javax.swing.JLabel isbnLabel;
    private com.toedter.calendar.JDateChooser publishDateChooser;
    private javax.swing.JLabel publishLabel;
    private javax.swing.JLabel publishersLabel;
    private javax.swing.JTextField publishersTextField;
    private javax.swing.JTextField similarTextField;
    private javax.swing.JLabel similarsLabel;
    private javax.swing.JDialog successDialog;
    private javax.swing.JLabel successLabel;
    private javax.swing.JPanel successPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JLabel typeInstructionLabel;
    // End of variables declaration//GEN-END:variables

    private void displaySuccessDialog() {
        successDialog.setLocationRelativeTo(null);
        successDialog.setMinimumSize(new Dimension(430, 60));
        successDialog.setVisible(true);
    }
}
