/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.vitorAlves.adapters.ui;

import com.vladsch.flexmark.ast.Node;
import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

/**
 *
 * @author vitor-alves
 */
public class TutorialUI extends javax.swing.JFrame {
    
    private static final Logger logger = LoggerFactory.getLogger(TutorialUI.class);

    /**
     * Creates new form TutorialUI
     */
    public TutorialUI() {
        initComponents();
        setupMDText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mdScrollPane = new javax.swing.JScrollPane();
        mdEditorPane = new javax.swing.JEditorPane();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tutorial");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        mdEditorPane.setEditable(false);
        mdEditorPane.setContentType("text/html"); // NOI18N
        mdEditorPane.setPreferredSize(new java.awt.Dimension(650, 500));
        mdScrollPane.setViewportView(mdEditorPane);

        jPanel1.add(mdScrollPane, java.awt.BorderLayout.CENTER);

        confirmButton.setText("Ok");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JEditorPane mdEditorPane;
    private javax.swing.JScrollPane mdScrollPane;
    // End of variables declaration//GEN-END:variables

    private void setupMDText() {
        File file = new File("src/main/resources/Tutorial.md");
        StringBuilder content = new StringBuilder();
        
        try (FileReader fileReader = new FileReader(file)) {
            BufferedReader reader = new BufferedReader(fileReader);
            
            String line;
            while((line = reader.readLine()) != null) content.append(line);
            
            String markdown = content.toString();
            
            Parser parser = Parser.builder().build();
            Node doc = parser.parse(markdown);
            HtmlRenderer renderer = HtmlRenderer.builder().build();
            String renderedMD = renderer.render(doc);
            
            mdEditorPane.setText(renderedMD);
        }catch (Exception e){
            logger.error("Erro inesperado\n\t{}: {}", e.getClass().getSimpleName(), e.getMessage());
        }
    }
}
