/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.vitorAlves.adapters.ui;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.vitorAlves.application.gateways.BooksDAO;
import org.vitorAlves.application.usecases.ListBooks;
import org.vitorAlves.application.usecases.UpdateBook;
import org.vitorAlves.domain.model.Book;
import org.vitorAlves.infra.gateways.JpaBooksDAO;

import java.awt.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author vitor-alves
 */
public class UpdateFormUI extends javax.swing.JFrame {
    
    private static final Logger logger = LoggerFactory.getLogger(UpdateFormUI.class);
    
    private final long id;
    private final BooksDAO dao = new JpaBooksDAO();
    private final ListBooks listBooks = new ListBooks(dao);
    private final UpdateBook updateBook = new UpdateBook(dao);

    /**
     * Creates new form UpdateFormUI
     */
    public UpdateFormUI(long id) {
        this.id = id;

        initComponents();
        setupComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        errorDialog = new javax.swing.JDialog();
        errorPanel = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        closeErrorButton = new javax.swing.JButton();
        successDialog = new javax.swing.JDialog();
        successPanel = new javax.swing.JPanel();
        successLabel = new javax.swing.JLabel();
        closeSuccessButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        typeInstructionLabel = new javax.swing.JLabel();
        bookDataLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        publishersLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        authorsLabel = new javax.swing.JLabel();
        authorsTextField = new javax.swing.JTextField();
        publishLabel = new javax.swing.JLabel();
        publishersTextField = new javax.swing.JTextField();
        isbnLabel = new javax.swing.JLabel();
        similarsLabel = new javax.swing.JLabel();
        similarTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        publishDateChooser = new com.toedter.calendar.JDateChooser();
        isbnFormattedTextField = new javax.swing.JFormattedTextField();

        errorPanel.setMinimumSize(new java.awt.Dimension(430, 50));
        errorPanel.setPreferredSize(new java.awt.Dimension(430, 50));

        errorLabel.setIcon(new javax.swing.ImageIcon("/home/vitor-alves/git/BooksManager/app/src/main/java/org/vitorAlves/adapters/assets/images/icons8-erro-48.png")); // NOI18N
        errorPanel.add(errorLabel);

        closeErrorButton.setText("Fechar");
        closeErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeErrorButtonActionPerformed(evt);
            }
        });
        errorPanel.add(closeErrorButton);

        errorDialog.getContentPane().add(errorPanel, java.awt.BorderLayout.CENTER);

        successPanel.setPreferredSize(new java.awt.Dimension(430, 50));
        successPanel.setLayout(new javax.swing.BoxLayout(successPanel, javax.swing.BoxLayout.X_AXIS));

        successLabel.setIcon(new javax.swing.ImageIcon("/home/vitor-alves/git/BooksManager/app/src/main/java/org/vitorAlves/adapters/assets/images/icons8-sucesso-48.png")); // NOI18N
        successLabel.setText("   O livro foi atualizado com sucesso!       ");
        successLabel.setName(""); // NOI18N
        successLabel.setPreferredSize(new java.awt.Dimension(60, 60));
        successPanel.add(successLabel);

        closeSuccessButton.setText("Fechar");
        closeSuccessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSuccessButtonActionPerformed(evt);
            }
        });
        successPanel.add(closeSuccessButton);

        successDialog.getContentPane().add(successPanel, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mainPanel.setBackground(new java.awt.Color(190, 190, 190));
        java.awt.GridBagLayout mainPanelLayout = new java.awt.GridBagLayout();
        mainPanelLayout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0};
        mainPanelLayout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        mainPanel.setLayout(mainPanelLayout);

        typeInstructionLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        typeInstructionLabel.setText("Editar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 4, 0);
        mainPanel.add(typeInstructionLabel, gridBagConstraints);

        bookDataLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bookDataLabel.setText("Dados do livro - ID: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        mainPanel.add(bookDataLabel, gridBagConstraints);

        titleLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        titleLabel.setText("Título:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 29, 0, 60);
        mainPanel.add(titleLabel, gridBagConstraints);

        publishersLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        publishersLabel.setText("Editoras:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 29, 0, 41);
        mainPanel.add(publishersLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        mainPanel.add(titleTextField, gridBagConstraints);

        authorsLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        authorsLabel.setText("Autores:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 29, 0, 45);
        mainPanel.add(authorsLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        mainPanel.add(authorsTextField, gridBagConstraints);

        publishLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        publishLabel.setText("Publicação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 29, 0, 23);
        mainPanel.add(publishLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        mainPanel.add(publishersTextField, gridBagConstraints);

        isbnLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        isbnLabel.setText("ISBN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 29, 0, 62);
        mainPanel.add(isbnLabel, gridBagConstraints);

        similarsLabel.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        similarsLabel.setText("Semelhantes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(0, 29, 0, 9);
        mainPanel.add(similarsLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        mainPanel.add(similarTextField, gridBagConstraints);

        confirmButton.setBackground(new java.awt.Color(153, 255, 153));
        confirmButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        confirmButton.setText("Confirmar");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.insets = new java.awt.Insets(9, 4, 9, 116);
        mainPanel.add(confirmButton, gridBagConstraints);

        cancelButton.setBackground(new java.awt.Color(255, 153, 153));
        cancelButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(9, 1, 8, 23);
        mainPanel.add(cancelButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 169);
        mainPanel.add(publishDateChooser, gridBagConstraints);

        try {
            isbnFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        mainPanel.add(isbnFormattedTextField, gridBagConstraints);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        try {
            logger.info("Atualizando livro...");
            
            String title = titleTextField.getText().trim();
            
            String authorsText = authorsTextField.getText();
            List<String> authors = authorsText.equals("") ? 
                    Collections.emptyList() 
                    : Arrays.stream(authorsTextField.getText().split(";"))
                    .map(String::trim).collect(Collectors.toList());

            LocalDate publishDate = publishDateChooser.getDate().toInstant()
                    .atOffset(ZoneOffset.UTC).toLocalDate();

            String isbn = isbnFormattedTextField.getText().trim();

            String publishersText = publishersTextField.getText();
            List<String> publishers = publishersText.equals("") ? 
                    Collections.emptyList() :
                    Arrays.stream(publishersText.split(";"))
                    .map(String::trim).collect(Collectors.toList());

            String similarText = similarTextField.getText();
            List<String> similars = similarText.equals("") ?
                    Collections.emptyList() :
                    Arrays.stream(similarText.split(";"))
                    .map(String::trim).collect(Collectors.toList());
            
            Book book = new Book(id, title, authors, publishDate, isbn, publishers, similars);
            
            updateBook.execute(book);
            
            successDialog.setLocationRelativeTo(null);
            successDialog.setMinimumSize(new Dimension(430, 60));
            successDialog.setVisible(true);
            
            logger.info("Atualização realizada com sucesso!");
            dispose();
        }
        catch (Exception e) {
            logger.error("Falha na atualização do livro!\n\t{}: {}",
                e.getClass().getSimpleName(), e.getMessage());
            errorLabel.setText("<html>Ocorreu um erro ao salvar o livro.<br>" +
                "Verifique os logs da aplicação!</html>");
            errorDialog.setLocationRelativeTo(null);
            errorDialog.setMinimumSize(new Dimension(430, 60));
            errorDialog.setVisible(true);
        }

        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        logger.warn("Operação cancelada");
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void closeErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeErrorButtonActionPerformed
        errorDialog.setVisible(false);
    }//GEN-LAST:event_closeErrorButtonActionPerformed

    private void closeSuccessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSuccessButtonActionPerformed
        successDialog.setVisible(false);
    }//GEN-LAST:event_closeSuccessButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorsLabel;
    private javax.swing.JTextField authorsTextField;
    private javax.swing.JLabel bookDataLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton closeErrorButton;
    private javax.swing.JButton closeSuccessButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JFormattedTextField isbnFormattedTextField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JPanel mainPanel;
    private com.toedter.calendar.JDateChooser publishDateChooser;
    private javax.swing.JLabel publishLabel;
    private javax.swing.JLabel publishersLabel;
    private javax.swing.JTextField publishersTextField;
    private javax.swing.JTextField similarTextField;
    private javax.swing.JLabel similarsLabel;
    private javax.swing.JDialog successDialog;
    private javax.swing.JLabel successLabel;
    private javax.swing.JPanel successPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JLabel typeInstructionLabel;
    // End of variables declaration//GEN-END:variables

    private void setupComponents() {
        Book bookToUpdate = listBooks.getBookById(id);
        
        StringBuilder dataLabel = new StringBuilder(bookDataLabel.getText());
        dataLabel.append(id);
        bookDataLabel.setText(dataLabel.toString());
        
        titleTextField.setText(bookToUpdate.getTitle());
        authorsTextField.setText(String.join("; ", bookToUpdate.getAuthors()));
        publishDateChooser.setDate(Date.from(bookToUpdate.getPublishDate()
                .atStartOfDay(ZoneId.systemDefault()).toInstant()));
        
        isbnFormattedTextField.setText(bookToUpdate.getIsbn());
        publishersTextField.setText(String.join("; ", bookToUpdate.getPublishers()));
        similarTextField.setText(String.join("; ", bookToUpdate.getSimilarBooks()));
    }
}
