/*
 * This source file was generated by the Gradle 'init' task
 */
package org.vitorAlves;

import org.vitorAlves.adapters.ui.MainWindowUI;
import org.vitorAlves.config.FlywayConfig;

import javax.swing.*;

public class App {
    public static void main(String[] args) throws InstantiationException, IllegalAccessException {
        FlywayConfig.init();
        
        SwingUtilities.invokeLater(() -> {
        MainWindowUI window = new MainWindowUI();
        window.setVisible(true);
    });
    }
}
